services:
  pr_reviewer_db:
    image: postgres:15
    container_name: pr_reviewer_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  pr_reviewer_migrator:
    build:
      context: ./pr_reviewer_database
      dockerfile: Dockerfile.migrator
    container_name: pr_reviewer_migrator
    depends_on:
      pr_reviewer_db:
        condition: service_healthy

    networks:
      - app-network
    command:
      - "-path=/app/migrations"
      - "-database=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@pr_reviewer_db:5432/${POSTGRES_DB}?sslmode=disable"
      - "up"


  pr_reviewer_service:
    build:
      context: ./pr_reviewer_service
      dockerfile: Dockerfile
    container_name: pr_reviewer_service
    environment:
      POSTGRES_HOST: pr_reviewer_db
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      APP_HTTP_PORT: 8080
    ports:
      - "${APP_HTTP_PORT}:8080"
    depends_on:
      pr_reviewer_db:
        condition: service_healthy
      pr_reviewer_migrator:
        condition: service_completed_successfully
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge